version: '3.0'

services:
  postgres:
    image: postgres:13.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=map
      - TZ=Europe/Samara  
volumes:
  postgres-data-volume: